name: PR Actions
run-name: PR checks for branch ${{ github.ref_name }} authored by ${{ github.actor }}
on:
  pull_request:
    types: [opened, reopened]
jobs:
  lint_pr:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      
